version: '3.8'

services:
    
  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: python3 server.py
    volumes:
    - ./app:/usr/src/app
    ports:
    - 8000:8000
    depends_on:
    - db

  web:
    build: ./vipcustomer.web-master
    ports:
      - 3000:3000
    volumes:
      - ./vipcustomer.web-master:/vipcustomer.web-master
      
      # Conditionally create a .env file if environment is production and print it's contents
    RUN if [ "$prod" = "true" ]; then \
        echo "NEXT_PUBLIC_HELLO_WORLD=$NEXT_PUBLIC_HELLO_WORLD" >> .env.production && \
        echo "SOME_OTHER_VARIABLE=$SOME_OTHER_VARIABLE" >> .env.production &&  cat .env.production; else echo "Environment local" ; fi



  db:
    image: postgres:13.4
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=db
